#version: '3.8'

services:
  dataimporter:
    build:
      context: ..
      dockerfile: .dockerisation/dockerfiles/dataimporter/Dockerfile
    depends_on:
      db:
        condition: service_healthy
        restart: true
    volumes:
      - ../:/workspaces:cached
    environment:
      PGUSER: postgres
      PGDATABASE: postgres
      PGPASSWORD: postgres
      PGHOST: db
      PGPORT: 5432
    # Overrides default command so things don't shut down after the process ends.
    command: ["bash", "-c", "python import_data_sql.py && sleep infinity"]
    network_mode: service:db
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  frontend:
    build:
      context: ../frontend
      dockerfile: ../.dockerisation/dockerfiles/frontend/Dockerfile
    ports:
      - 3000:3000

  fastapibackend:
    build:
      context: ../fastapi_backend
      dockerfile: ../.dockerisation/dockerfiles/backend_api/Dockerfile
    environment:
      PGUSER: postgres
      PGDATABASE: postgres
      PGPASSWORD: postgres
      PGHOST: db
      PGPORT: 5432
    ports:
      - 80:80

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - 5432:5432
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data: